### ISSUE TITLE
Not properly slugifying

### ISSUE THREAD

**Issue by niftylettuce** [dodo/node-slug#16]
`"It's your journey ... we guide you through."`

converts to

`It\'s-your-journey-...-we-guide-you-through.`

which is invalid

**Comment by aurelien-defossez** [comment]
I just came around this issue, and even though I understand why the period has to be treated, I don't understand why it has to be removed and not replaced by a '-' like the other characters?

So for instance, when I want to slug a login which has periods, they are simply removed and my resulting login looks strange: e.g. **monica.bellucci** -> **monicabellucci**. I'd prefer **monica-bellucci**.
