### ISSUE TITLE
Add default for lowercase, and ability to turn off lowercase if wanted

### ISSUE THREAD

**Issue by niftylettuce** [dodo/node-slug#32]
Having to do `.toLowerCase()` every time is very annoying, please fix this @dodo as similar to how you did with `pretty`.

**Comment by a00andos** [comment]
+1

**Comment by gmotruk** [comment]
+1

**Comment by oitozero** [comment]
+1

**Comment by gimenete** [comment]
+1

**Comment by bcallaars** [comment]
+1

**Comment by fragphace** [comment]
+1

**Comment by BrunoBernardino** [comment]
+1

**Comment by jeduan** [comment]
:+1:

**Comment by anotheri** [comment]
+1

**Comment by tmcpro** [comment]
+1

**Comment by diego-pacheco** [comment]
+1

**Comment by s-silva** [comment]
:+1:

**Comment by iangthornton** [comment]
+1

**Comment by oliverbenns** [comment]
+1

**Comment by Sicria** [comment]
+1

**Comment by Zertz** [comment]
Seems like @dodo has vanished or is otherwise busy. I'll probably end up forking the project to implement my PR as well as a couple others.

**Comment by dominhhai** [comment]
@Zertz Do you have any plan to merge other PRs and publishing this?
seems that @dodo so busy to get the work done.
May we force then merge the possible PRs, and publish?

**Comment by dodo** [comment]
I merged @Zertz's PR and restricted the default to lower case only to rfc3986 mode, so the pretty mode stays case sensitive.
I also changed the option name to lower instead of lowercase.

Let me know when this is not working out for you.

**Comment by Zertz** [comment]
Thanks @dodo !

**Comment by niftylettuce** [comment]
Why do we still have Pretty Mode on?  The default should be the standard RFC3986.  Come on.

**Comment by niftylettuce** [comment]
https://github.com/dodo/node-slug/blob/master/slug.js#L72-L74 Change this to RFC3986 please.

**Comment by niftylettuce** [comment]
In the Readme you say it is RFC3986 which is so misleading too.

![screen shot 2015-11-19 at 12 58 58 pm](https://cloud.githubusercontent.com/assets/523141/11279238/579d8ae8-8ebd-11e5-8e3e-a4ca545c335e.png)

**Comment by niftylettuce** [comment]
Can you please fix this?  The default should be RFC 3986... especially if you advertise it in the Readme as "respecting RFC 3986".  I have forked this and made it RFC compliant by default.  For anyone that wants this, please install it with `npm install --save slug-rfc` and that way we don't need to use forks.  When this package switches its default to RFC (if it does), then I will deprecate that package I made and delete my fork at https://github.com/niftylettuce/node-slug-rfc.

**Comment by simison** [comment]
@niftylettuce see #71

**Comment by niftylettuce** [comment]
I've wanted this for probably like a year now haha, already forked it and published an RFC compliant version...

**Comment by callaars** [comment]
Rant much. :)

**Comment by niftylettuce** [comment]
@bcallaars petty comments not appreciated

**Comment by simison** [comment]
@niftylettuce:

> Why should I bother to use that, it has a completely unrelated name. All I want is the default for this package to have the proper RFC advertised standards

Me too. And I want is someone to maintain _some_ package. ;-)

> I already forked it and published an RFC compliant version myself.

Sure! That's cool. @Zertz seems to have a lot of enthusiasm, too. You guys should just put up an organisation and publish your RFC version under the name RFCSlug, niftySlug or something... :-)

I pinged you in hopes that you'd talk with @Zertz about possibilities.

**Comment by niftylettuce** [comment]
Aye aye! @simison I commented over in that issue you referenced and mentioned how I realized you were not the original OP author.  Maybe @Zertz just would want to use `npm i --save slug-rfc` instead.  It's a bit easier to remember and type haha.

**Comment by Zertz** [comment]
@niftylettuce I'm sorry my efforts don't meet your expectations and you are correct, documentation has not been updated yet. I am working on this because I use node-slug a lot and the community has submitted many useful PR's, including yours. I am planning Node v6 compatibility, which is currently very hard because of the issue described in #70.

Also,

> Slug, or land slug, is a common name for any apparently shell-less terrestrial gastropod mollusc.

**Comment by callaars** [comment]
It's nice @Zertz, it's not all about fame.

**Comment by simison** [comment]
Don't let the naming stop you guys. :-)

BTW I settled for using https://github.com/pid/speakingurl myself for now — has anyone had look at it? Seems to be well maintained. (Ping @pid)

**Comment by pid** [comment]
;-) pong

**Comment by davidgilbertson** [comment]
https://github.com/pid/speakingurl does the trick for me. I'm sure `slug-rfc` and `mollusc` work just as well, but downloads/day wins

**Comment by niftylettuce** [comment]
downloads have nothing to do with functionality.

**Comment by niftylettuce** [comment]
`slug` downloads:

<img width="346" alt="screen shot 2016-05-29 at 2 03 28 pm" src="https://cloud.githubusercontent.com/assets/523141/15635199/25a3eaac-25a6-11e6-97bb-6309734157f9.png">

`speakingurl` downloads:

<img width="345" alt="screen shot 2016-05-29 at 2 03 25 pm" src="https://cloud.githubusercontent.com/assets/523141/15635201/314d1a72-25a6-11e6-8442-c2ddddaedf6d.png">

it is pretty lame to not fix the #1 package in NPM for slugs, even having the reserved name `slug` as its package name...  this is not how our community should function.  So when someone new comes to the community, they have to look at 5 different packages all doing the same thing?  Why doesn't everyone just fork koa and express and rename them a hundred times for little use cases?

**Comment by niftylettuce** [comment]
I am deprecating and removing my `slug-rfc` package from NPM and just going to use `speakingurl`.  I suggest that @dodo find contributors and be willing to accept contributors next time.  Thanks @pid for your work there, nice backup.

**Comment by Zertz** [comment]
If that works for you, then by all means go for it :-)

**Comment by davidgilbertson** [comment]
@niftylettuce what I meant to say is that when three packages all have the functionality that I want, and one has orders of magnitude more downloads, I'll pick that one.
