### ISSUE TITLE
C vs. C# produce same slug "c"

### ISSUE THREAD

**Issue by anthonyettinger** [dodo/node-slug#35]
This is causing a duplicate key error in my database.

`C#` is slugified to `c`, which conflicts with slug for `C`. Is there anyway to override this? Like maybe replacing `#` with `sharp` or `pound`.

**Comment by chovy** [comment]
I found a solution. Without being too destructive.

```
	if ( this.nameLower == 'c#' ) {
		slug.charmap['#'] = 'sharp';
	}
```

**Comment by dodo** [comment]
Nice, that you found a good solution so quickly.
Your example is a very specific case of replacement logic which would be better suited as a small library instead of a feature of this package, IMHO.
