### ISSUE TITLE
Arabic characters

### ISSUE THREAD

**Issue by Philmod** [dodo/node-slug#39]
Hey guys,

It doesn't work for some language: 

```
> var t = "تحية الاسلام مدخل لدعوة غير المسلمين من الوافدين";
> slug(t);
''
```

Thanks,
Philmod

**Comment by dodo** [comment]
Would you mind creating a pull request, where those chars get replaced by ASCII characters?
Keep in mind that node-slug is not capable of [transliteration](http://en.wikipedia.org/wiki/Transliteration) which is discussed in #8.

**Comment by Philmod** [comment]
Yeah, I ended using that library.

**Comment by montaro** [comment]
I believe the Arabic letters are URL friendly, you just need not to omit them 
https://github.com/dodo/node-slug/issues/60
