### ISSUE TITLE
Possibly incompatible with jspm frontend package manager?

### ISSUE THREAD

**Issue by jedrichards** [dodo/node-slug#40]
After doing a `jspm install npm:slug` I get an error when trying to use your library.

It looks like its trying to interact with a file `So.js` related to the unicode dependency. Perhaps it doesn't recognise the jspm SystemJS environment properly? Maybe?

**Comment by dodo** [comment]
Looks like jspm isn't installing `node-unicodetable` properly. That package has an additional build step when being installed, which is not required when using in a browser environment.

Do you know a way to tell jspm to ignore [`unicode/category/So`](https://github.com/dodo/node-slug/blob/0.9.1/slug.js#L6)?

**Comment by dodo** [comment]
_derp_ .. Or you just simply disable symbols by default:

``` javascript
slug.defaults.modes['rfc3986'].symbols = false
slug.defaults.modes['pretty'].symbols = false
```

**Comment by jedrichards** [comment]
Gotcha, yeah, that works thanks. Will report back if I discover anything else of importance ...

**Comment by kiowa** [comment]
How did you import this without triggering the So.js require?
