### ISSUE TITLE
Update docs on `options.lower`

### ISSUE THREAD

**Issue by MadLittleMods** [dodo/node-slug#54]
The example uses the old `options.lowercase` which doesn't work anymore and has seemed to have moved to `options.lower`

`options.lower` also defaults to false now which seems a bit backwards but in any case, the docs should be corrected.

**Comment by Belema** [comment]
Looks like this has been fixed now.

EDIT: you are probably referring to the npmjs.com page. There is already an open issue about it: #49.

**Comment by MadLittleMods** [comment]
@Belema Thanks :)
