### ISSUE TITLE
NPM reports "Regular Expression Denial of Service" for slug

### ISSUE THREAD

**Issue by hawkeye64** [dodo/node-slug#92]
https://nodesecurity.io/advisories/537
This needs to be fixed ASAP.

**Comment by Ilshidur** [comment]
Duplicate of https://github.com/dodo/node-slug/pull/91.

**Comment by Trott** [comment]
0.9.2 has been published with this issue fixed. https://www.npmjs.com/package/slug/v/0.9.2

@hawkeye64 Can you close this issue?
